-- Table: InstrumentCommodity (DMC00000135)
-- Description: The InstrumentCommodity concepts provides additional information specific to the Commodity asset class of instruments.
CREATE TABLE GOLD."INSTRUMENTCOMMODITY" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER NOT NULL UNIQUE REFERENCES GOLD."INSTRUMENT"("_ID"),
  "INSTRUMENTCOMMODITYOTHERBASEPRODUCT" TEXT,
  "INSTRUMENTCOMMODITYFINALPRICETYPE" TEXT,
  "INSTRUMENTCOMMODITYOTHERFURTHERSUBPRODUCT" TEXT,
  "INSTRUMENTCOMMODITYTRANSACTIONTYPE" TEXT,
  "INSTRUMENTCOMMODITYOTHERSUBPRODUCT" TEXT,
  "INSTRUMENTCREDITDERIVATIVESENIORITY" INTEGER REFERENCES GOLD."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES"("_ID")
);

COMMENT ON TABLE GOLD."INSTRUMENTCOMMODITY" IS '[DMC00000135] The InstrumentCommodity concepts provides additional information specific to the Commodity asset class of instruments.';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."_PID" IS '[DMC00000121] Foreign key to parent concept table: Instrument (ONE_TO_ONE relationship)';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."INSTRUMENTCOMMODITYOTHERBASEPRODUCT" IS '[DMA00000605] InstrumentCommodityOtherBaseProduct - The type of commodity agreement.';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."INSTRUMENTCOMMODITYFINALPRICETYPE" IS '[DMA00000604] InstrumentCommodityFinalPriceType - Final price type.';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."INSTRUMENTCOMMODITYOTHERFURTHERSUBPRODUCT" IS '[DMA00000606] InstrumentCommodityOtherFurtherSubProduct - Raw material on which the commodity contract is based.';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."INSTRUMENTCOMMODITYTRANSACTIONTYPE" IS '[DMA00000608] InstrumentCommodityTransactionType - Secondary category of raw material on which the commodity contract is based.';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."INSTRUMENTCOMMODITYOTHERSUBPRODUCT" IS '[DMA00000607] InstrumentCommodityOtherSubProduct - Tertiary category of raw material on which the commodity contract is based.';
COMMENT ON COLUMN GOLD."INSTRUMENTCOMMODITY"."INSTRUMENTCREDITDERIVATIVESENIORITY" IS '[DMA00000611] InstrumentCreditDerivativeSeniority - FK to lookup table: InstrumentCreditDerivativesSeniorityTypes';