-- Table: InstrumentInterestRateDerivative (DMC00000138)
-- Description: The InstrumentInterestRateDerivatives concepts provides additional information specific to the Interest Rate Derivatives asset class of instruments.
CREATE TABLE GOLD."INSTRUMENTINTERESTRATEDERIVATIVE" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER NOT NULL UNIQUE REFERENCES GOLD."INSTRUMENT"("_ID"),
  "INSTRUMENTINTERESTRATEDERIVATIVETERMCONTRACTVALUE" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVEINDEXCATEGORY" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVEFLOATINGRATELEG2" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVETERMCONTRACT" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVEOTHERREFERENCERATETERMVALUE" NUMBER(18,4),
  "INSTRUMENTINTERESTRATEDERIVATIVECONTRACTLEG2" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVENOTIONALSCHEDULE" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVEOTHERREFERENCERATETERMUNIT" NUMBER(18,4),
  "INSTRUMENTINTERESTRATEDERIVATIVEFIXEDRATELEG2" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVEINDEXBASISPOINTSPREAD" NUMBER(18,4),
  "INSTRUMENTINTERESTRATEDERIVATIVEINDEXMASTERID" INTEGER,
  "INSTRUMENTINTERESTRATEDERIVATIVEFIXEDRATELEG1" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVEREFERENCERATETERMVALUE" NUMBER(18,4),
  "INSTRUMENTINTERESTRATEDERIVATIVEINDEXTYPE" INTEGER,
  "INSTRUMENTINTERESTRATEDERIVATIVEIRTERMCONTRACTUNIT" TEXT,
  "INSTRUMENTINTERESTRATEDERIVATIVEINDEXTERM" NUMBER(18,4),
  "INSTRUMENTOPTIONTYPE" INTEGER REFERENCES GOLD."LOOKUP_INTRUMENTOPTIONTYPES"("_ID")
);

COMMENT ON TABLE GOLD."INSTRUMENTINTERESTRATEDERIVATIVE" IS '[DMC00000138] The InstrumentInterestRateDerivatives concepts provides additional information specific to the Interest Rate Derivatives asset class of instruments.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."_PID" IS '[DMC00000121] Foreign key to parent concept table: Instrument (ONE_TO_ONE relationship)';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVETERMCONTRACTVALUE" IS '[DMA00000640] InstrumentInterestRateDerivativeTermContractValue';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEINDEXCATEGORY" IS '[DMA00000629] InstrumentInterestRateDerivativeIndexCategory';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEFLOATINGRATELEG2" IS '[DMA00000627] InstrumentInterestRateDerivativeFloatingRateLeg2';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVETERMCONTRACT" IS '[DMA00000639] InstrumentInterestRateDerivativeTermContract';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEOTHERREFERENCERATETERMVALUE" IS '[DMA00000636] InstrumentInterestRateDerivativeOtherReferenceRateTermValue - A reference rate is a rate that determines payoffs in a financial contract and that is outside the control of the parties to the contract.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVECONTRACTLEG2" IS '[DMA00000624] InstrumentInterestRateDerivativeContractLeg2';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVENOTIONALSCHEDULE" IS '[DMA00000634] InstrumentInterestRateDerivativeNotionalSchedule - The schedule of notional amounts.  Interest rate swaps are based on a notional amount of money.  The notionaly can vary during the lifetime of the swap, but only at payment period boundaries.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEOTHERREFERENCERATETERMUNIT" IS '[DMA00000635] InstrumentInterestRateDerivativeOtherReferenceRateTermUnit - A reference rate is a rate that determines payoffs in a financial contract and that is outside the control of the parties to the contract.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEFIXEDRATELEG2" IS '[DMA00000626] InstrumentInterestRateDerivativeFixedRateLeg2';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEINDEXBASISPOINTSPREAD" IS '[DMA00000628] InstrumentInterestRateDerivativeIndexBasisPointSpread - The difference or gap that exists between two prices, rates, or yields.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEINDEXMASTERID" IS '[DMA00000630] InstrumentInterestRateDerivativeIndexMasterID - If the contract has an underlying index, this provides the link to the Index within the Instrument Database';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEFIXEDRATELEG1" IS '[DMA00000625] InstrumentInterestRateDerivativeFixedRateLeg1';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEREFERENCERATETERMVALUE" IS '[DMA00000638] InstrumentInterestRateDerivativeReferenceRateTermValue - A reference rate is a rate that determines payoffs in a financial contract and that is outside the control of the parties to the contract.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEINDEXTYPE" IS '[DMA00000632] InstrumentInterestRateDerivativeIndexType - The index type.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEIRTERMCONTRACTUNIT" IS '[DMA00000633] InstrumentInterestRateDerivativeIrTermContractUnit';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTINTERESTRATEDERIVATIVEINDEXTERM" IS '[DMA00000631] InstrumentInterestRateDerivativeIndexTerm - The time horizon of the index.';
COMMENT ON COLUMN GOLD."INSTRUMENTINTERESTRATEDERIVATIVE"."INSTRUMENTOPTIONTYPE" IS '[DMA00000649] InstrumentOptionType - FK to lookup table: IntrumentOptionTypes';