-- Table: LegalEntityRestructedList (DMC00000025)
-- Description: LegalEntityRestructedList
CREATE TABLE GOLD."LEGALENTITYRESTRUCTEDLIST" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER NOT NULL REFERENCES GOLD."LEGALENTITY"("_ID")
);

COMMENT ON TABLE GOLD."LEGALENTITYRESTRUCTEDLIST" IS '[DMC00000025] LegalEntityRestructedList';
COMMENT ON COLUMN GOLD."LEGALENTITYRESTRUCTEDLIST"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."LEGALENTITYRESTRUCTEDLIST"."_PID" IS '[DMC00000106] Foreign key to parent concept table: LegalEntity';