-- Table: LegalEntityIdentifiers (DMC00000023)
-- Description: The Legal Entity Identifiers concept provides a single place to look up and cross reference a single legal entity using any identification code
CREATE TABLE GOLD."LEGALENTITYIDENTIFIERS" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER NOT NULL REFERENCES GOLD."LEGALENTITY"("_ID"),
  "LEGALENTITYIDENTIFIERSTYPE" INTEGER REFERENCES GOLD."LOOKUP_MASTERCROSSREFTYPES"("_ID"),
  "LEGALENTITYIDENTIFIERSSCOPE" TEXT,
  "LEGALENTITYIDENTIFIERSTARTDATE" DATE,
  "LEGALENTITYIDENTICFIERSENDDATE" DATE,
  "LEGALENTITYIDENTICFIERSVALUE" TEXT
);

COMMENT ON TABLE GOLD."LEGALENTITYIDENTIFIERS" IS '[DMC00000023] The Legal Entity Identifiers concept provides a single place to look up and cross reference a single legal entity using any identification code';
COMMENT ON COLUMN GOLD."LEGALENTITYIDENTIFIERS"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."LEGALENTITYIDENTIFIERS"."_PID" IS '[DMC00000106] Foreign key to parent concept table: LegalEntity';
COMMENT ON COLUMN GOLD."LEGALENTITYIDENTIFIERS"."LEGALENTITYIDENTIFIERSTYPE" IS '[DMA00000811] LegalEntityIdentifiersType - FK to lookup table: MasterCrossRefTypes';
COMMENT ON COLUMN GOLD."LEGALENTITYIDENTIFIERS"."LEGALENTITYIDENTIFIERSSCOPE" IS '[DMA00000812] LegalEntityIdentifiersScope - LegalEntityIdentifiersScope';
COMMENT ON COLUMN GOLD."LEGALENTITYIDENTIFIERS"."LEGALENTITYIDENTIFIERSTARTDATE" IS '[DMA00000813] LegalEntityIdentifierStartDate - LegalEntityIdentifierStartDate';
COMMENT ON COLUMN GOLD."LEGALENTITYIDENTIFIERS"."LEGALENTITYIDENTICFIERSENDDATE" IS '[DMA00000814] LegalEntityIdenticfiersEndDate - LegalEntityIdenticfiersEndDate';
COMMENT ON COLUMN GOLD."LEGALENTITYIDENTIFIERS"."LEGALENTITYIDENTICFIERSVALUE" IS '[DMA00000815] LegalEntityIdenticfiersValue - LegalEntityIdenticfiersValue';