-- Table: LegalEntityBrandColours (DMC00000017)
-- Description: What are my brand colours
CREATE TABLE GOLD."LEGALENTITYBRANDCOLOURS" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER NOT NULL REFERENCES GOLD."LEGALENTITY"("_ID"),
  "COLOURNAME" INTEGER
);

COMMENT ON TABLE GOLD."LEGALENTITYBRANDCOLOURS" IS '[DMC00000017] What are my brand colours';
COMMENT ON COLUMN GOLD."LEGALENTITYBRANDCOLOURS"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."LEGALENTITYBRANDCOLOURS"."_PID" IS '[DMC00000106] Foreign key to parent concept table: LegalEntity';
COMMENT ON COLUMN GOLD."LEGALENTITYBRANDCOLOURS"."COLOURNAME" IS '[DMA00000802] ColourName';