-- Lookup Table: InstrumentOptionStrikePriceTypes (DMT00000046)
-- Description: .
CREATE TABLE GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES"("_ID"),
  "LOOKUP_CODE" TEXT,
  "LOOKUP_NAME" TEXT,
  "LOOKUP_DESCRIPTION" TEXT
);

COMMENT ON TABLE GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES" IS '[DMT00000046] .';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES"."_PID" IS 'Self-referential FK to parent lookup within this table (hierarchical)';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES"."LOOKUP_CODE" IS 'Short code identifier for the lookup value';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES"."LOOKUP_NAME" IS 'Display name for the lookup value';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTOPTIONSTRIKEPRICETYPES"."LOOKUP_DESCRIPTION" IS 'Detailed description of the lookup value';