-- Lookup Table: InstrumentCurrencyTypes (DMT00000043)
-- Description: .
CREATE TABLE GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES"("_ID"),
  "LOOKUP_CODE" TEXT,
  "LOOKUP_NAME" TEXT,
  "LOOKUP_DESCRIPTION" TEXT
);

COMMENT ON TABLE GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES" IS '[DMT00000043] .';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES"."_PID" IS 'Self-referential FK to parent lookup within this table (hierarchical)';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES"."LOOKUP_CODE" IS 'Short code identifier for the lookup value';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES"."LOOKUP_NAME" IS 'Display name for the lookup value';
COMMENT ON COLUMN GOLD."LOOKUP_INSTRUMENTCURRENCYTYPES"."LOOKUP_DESCRIPTION" IS 'Detailed description of the lookup value';