-- Table: PersonAddresses (DMC00000145)
-- Description: The PersonAddress concept allows for people to have multiple mailing addresses with a type.
CREATE TABLE GOLD."PERSONADDRESSES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER NOT NULL UNIQUE REFERENCES GOLD."PERSON"("_ID"),
  "PERSONADDRESSESTYPE" INTEGER REFERENCES GOLD."LOOKUP_PERSONADDRESSTYPE"("_ID"),
  "PERSONADDRESSESLINE1" TEXT,
  "PERSONADDRESSESLINE2" TEXT,
  "PERSONADDRESSESLINE3" TEXT,
  "PERSONADDRESSESTOWNCITY" TEXT,
  "PERSONADDRESSESPOSTALZIP" TEXT,
  "PERSONADDRESSESCOUNTRY" INTEGER REFERENCES GOLD."LOOKUP_UNIVERSALCOUNTRYCODES"("_ID"),
  "PERSONCITIZENSHIPTYPE" INTEGER
);

COMMENT ON TABLE GOLD."PERSONADDRESSES" IS '[DMC00000145] The PersonAddress concept allows for people to have multiple mailing addresses with a type.';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."_PID" IS '[DMC00000143] Foreign key to parent concept table: Person (ONE_TO_ONE relationship)';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONADDRESSESTYPE" IS '[DMA00000758] PersonAddressesType - FK to lookup table: PersonAddressType';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONADDRESSESLINE1" IS '[DMA00000752] PersonAddressesLine1 - Loren ipsum...';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONADDRESSESLINE2" IS '[DMA00000753] PersonAddressesLine2 - Loren ipsum...';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONADDRESSESLINE3" IS '[DMA00000754] PersonAddressesLine3 - Loren ipsum...';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONADDRESSESTOWNCITY" IS '[DMA00000757] PersonAddressesTownCity - Loren ipsum...';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONADDRESSESPOSTALZIP" IS '[DMA00000756] PersonAddressesPostalZIP - Loren ipsum...';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONADDRESSESCOUNTRY" IS '[DMA00000751] PersonAddressesCountry - FK to lookup table: UniversalCountryCodes';
COMMENT ON COLUMN GOLD."PERSONADDRESSES"."PERSONCITIZENSHIPTYPE" IS '[DMA00000765] PersonCitizenshipType - The PersonCitizenshipType is an indicator of how the person acquired citizenship - ie through brith or through a naturalization process';