-- Data Product: Historical Clients (DMP00000004)
-- Description: The Historical Clients data product provides an extended list of all clients with whom we have done business over the last 5 years.  In general, we view clients with zero activity in the last 5 years as obsolete and dead.
CREATE TABLE PLATINUM."CLIENTHISTORICAL" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."CLIENTHISTORICAL"("_ID"),
  "CLIENTID" TEXT,
  "CLIENTNAME" TEXT,
  "LEGALENTITYRELATIONSHIPSTYPE" TEXT,
  "LEGALENTITYROLETYPE" TEXT,
  "CLIENTPRIMARYCOUNTRY" TEXT,
  "CLIENTPRIMARYINDUSTRY" TEXT
);

COMMENT ON TABLE PLATINUM."CLIENTHISTORICAL" IS '[DMP00000004] The Historical Clients data product provides an extended list of all clients with whom we have done business over the last 5 years.  In general, we view clients with zero activity in the last 5 years as obsolete and dead.';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."_PID" IS 'Self-referential FK to parent record within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."CLIENTID" IS 'DMA00000717';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."CLIENTNAME" IS 'DMA00000689';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."LEGALENTITYRELATIONSHIPSTYPE" IS 'DMA00000691';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."LEGALENTITYROLETYPE" IS 'DMA00000787';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."CLIENTPRIMARYCOUNTRY" IS 'DMA00000676';
COMMENT ON COLUMN PLATINUM."CLIENTHISTORICAL"."CLIENTPRIMARYINDUSTRY" IS 'DMA00000685';