-- Data Product: Current Clients (DMP00000003)
-- Description: The Client Current data product provides a list of the organization's current clients, including key information such as client name, client type, client ultimate parent entity, primary address, and client relationship owner.
CREATE TABLE PLATINUM."CLIENTCURRENT" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."CLIENTCURRENT"("_ID"),
  "CLIENTID" TEXT,
  "CLIENTNAME" TEXT,
  "CLIENTPRIMARYCOUNTRY" TEXT,
  "CLIENTRELATIONSHIPSTYPE" TEXT,
  "CLIENTPARENT" TEXT,
  "CLIENTTYPE" TEXT,
  "CLIENTSUMMARYTYPE" TEXT,
  "CLIENTSUMMARYVALUE" TEXT,
  "LEGALENTITYRISKFACTORSTYPE" TEXT,
  "LEGALENTITYRISKFACTORSTYPE" TEXT,
  "LEGALENTITYRISKFACTORSVALUE" TEXT
);

COMMENT ON TABLE PLATINUM."CLIENTCURRENT" IS '[DMP00000003] The Client Current data product provides a list of the organization''s current clients, including key information such as client name, client type, client ultimate parent entity, primary address, and client relationship owner.';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."_PID" IS 'Self-referential FK to parent record within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTID" IS 'DMA00000717';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTNAME" IS 'DMA00000689';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTPRIMARYCOUNTRY" IS 'DMA00000676';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTRELATIONSHIPSTYPE" IS 'DMA00000691';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTPARENT" IS 'DMA00000690';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTTYPE" IS 'DMA00000695';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTSUMMARYTYPE" IS 'DMA00000804';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."CLIENTSUMMARYVALUE" IS 'DMA00000807';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."LEGALENTITYRISKFACTORSTYPE" IS 'DMA00000693';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."LEGALENTITYRISKFACTORSTYPE" IS 'DMA00000693';
COMMENT ON COLUMN PLATINUM."CLIENTCURRENT"."LEGALENTITYRISKFACTORSVALUE" IS 'DMA00000694';