-- Data Product: Current Investors (DMP00000005)
-- Description: The Current Investors Data Product provides a list of current investors in our various managed funds
CREATE TABLE PLATINUM."INVESTORCURRENT" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."INVESTORCURRENT"("_ID"),
  "LEGALENTITYROLETYPE" TEXT,
  "INVESTORID" TEXT,
  "INVESTORNAME" TEXT,
  "LEGALENTITYRELATIONSHIPSTYPE" TEXT,
  "LEGALENTITYCOUNTRY" TEXT,
  "LEGALENTITYINDUSTRY" TEXT
);

COMMENT ON TABLE PLATINUM."INVESTORCURRENT" IS '[DMP00000005] The Current Investors Data Product provides a list of current investors in our various managed funds';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."_PID" IS 'Self-referential FK to parent record within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."LEGALENTITYROLETYPE" IS 'DMA00000787';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."INVESTORID" IS 'DMA00000717';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."INVESTORNAME" IS 'DMA00000689';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."LEGALENTITYRELATIONSHIPSTYPE" IS 'DMA00000691';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."LEGALENTITYCOUNTRY" IS 'DMA00000676';
COMMENT ON COLUMN PLATINUM."INVESTORCURRENT"."LEGALENTITYINDUSTRY" IS 'DMA00000685';