-- Data Product: Legal Structure (DMP00000008)
-- Description: The Legal Structure Data Product provides our official full hierarchy of our own entities, including majority own subsidiaries and fund management structures.
CREATE TABLE PLATINUM."LEGALSTRUCTURE" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."LEGALSTRUCTURE"("_ID"),
  "ENITYID" TEXT,
  "ENTITYNAME" TEXT,
  "ENTITYPARENT" TEXT,
  "LEGALENTITYRELATIONSHIPSRELATEDENTITY" TEXT,
  "LEGALENTITYCOUNTRY" TEXT,
  "LEGALENTITYTYPE" TEXT
);

COMMENT ON TABLE PLATINUM."LEGALSTRUCTURE" IS '[DMP00000008] The Legal Structure Data Product provides our official full hierarchy of our own entities, including majority own subsidiaries and fund management structures.';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."_PID" IS 'Self-referential FK to parent record within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."ENITYID" IS 'DMA00000717';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."ENTITYNAME" IS 'DMA00000689';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."ENTITYPARENT" IS 'DMA00000691';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."LEGALENTITYRELATIONSHIPSRELATEDENTITY" IS 'DMA00000690';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."LEGALENTITYCOUNTRY" IS 'DMA00000676';
COMMENT ON COLUMN PLATINUM."LEGALSTRUCTURE"."LEGALENTITYTYPE" IS 'DMA00000695';