-- Lookup Table: PersonRoles (DMT00000099)
-- Description: PersonRoles
CREATE TABLE PLATINUM."LOOKUP_PERSONROLES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."LOOKUP_PERSONROLES"("_ID"),
  "LOOKUP_CODE" TEXT,
  "LOOKUP_NAME" TEXT,
  "LOOKUP_DESCRIPTION" TEXT
);

COMMENT ON TABLE PLATINUM."LOOKUP_PERSONROLES" IS '[DMT00000099] PersonRoles';
COMMENT ON COLUMN PLATINUM."LOOKUP_PERSONROLES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."LOOKUP_PERSONROLES"."_PID" IS 'Self-referential FK to parent lookup within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."LOOKUP_PERSONROLES"."LOOKUP_CODE" IS 'Short code identifier for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_PERSONROLES"."LOOKUP_NAME" IS 'Display name for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_PERSONROLES"."LOOKUP_DESCRIPTION" IS 'Detailed description of the lookup value';