-- Lookup Table: InstrumentTradingStatusTypes (DMT00000048)
-- Description: .
CREATE TABLE PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES"("_ID"),
  "LOOKUP_CODE" TEXT,
  "LOOKUP_NAME" TEXT,
  "LOOKUP_DESCRIPTION" TEXT
);

COMMENT ON TABLE PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES" IS '[DMT00000048] .';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES"."_PID" IS 'Self-referential FK to parent lookup within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES"."LOOKUP_CODE" IS 'Short code identifier for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES"."LOOKUP_NAME" IS 'Display name for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTTRADINGSTATUSTYPES"."LOOKUP_DESCRIPTION" IS 'Detailed description of the lookup value';