-- Lookup Table: InstrumentOptionStyleTypes (DMT00000047)
-- Description: .
CREATE TABLE PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES"("_ID"),
  "LOOKUP_CODE" TEXT,
  "LOOKUP_NAME" TEXT,
  "LOOKUP_DESCRIPTION" TEXT
);

COMMENT ON TABLE PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES" IS '[DMT00000047] .';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES"."_PID" IS 'Self-referential FK to parent lookup within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES"."LOOKUP_CODE" IS 'Short code identifier for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES"."LOOKUP_NAME" IS 'Display name for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTOPTIONSTYLETYPES"."LOOKUP_DESCRIPTION" IS 'Detailed description of the lookup value';