-- Lookup Table: InstrumentCreditDerivativesSeniorityTypes (DMT00000042)
-- Description: .
CREATE TABLE PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES"("_ID"),
  "LOOKUP_CODE" TEXT,
  "LOOKUP_NAME" TEXT,
  "LOOKUP_DESCRIPTION" TEXT
);

COMMENT ON TABLE PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES" IS '[DMT00000042] .';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES"."_PID" IS 'Self-referential FK to parent lookup within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES"."LOOKUP_CODE" IS 'Short code identifier for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES"."LOOKUP_NAME" IS 'Display name for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INSTRUMENTCREDITDERIVATIVESSENIORITYTYPES"."LOOKUP_DESCRIPTION" IS 'Detailed description of the lookup value';