-- Lookup Table: IntrumentOptionTypes (DMT00000049)
-- Description: .
CREATE TABLE PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES"("_ID"),
  "LOOKUP_CODE" TEXT,
  "LOOKUP_NAME" TEXT,
  "LOOKUP_DESCRIPTION" TEXT
);

COMMENT ON TABLE PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES" IS '[DMT00000049] .';
COMMENT ON COLUMN PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES"."_PID" IS 'Self-referential FK to parent lookup within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES"."LOOKUP_CODE" IS 'Short code identifier for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES"."LOOKUP_NAME" IS 'Display name for the lookup value';
COMMENT ON COLUMN PLATINUM."LOOKUP_INTRUMENTOPTIONTYPES"."LOOKUP_DESCRIPTION" IS 'Detailed description of the lookup value';