-- Data Product: Portfolio Company Performance Dataset (DMP00000016)
-- Description: The Portfolio Company Performance Dataset is a Platinum‑layer, certified dataset providing a governed, consistent view of individual portfolio company performance across the firm. It standardizes financial metrics, operating KPIs, and performance‑versus‑plan measures, enabling trusted company‑level accountability and comparison across funds, sectors, and vintages. Built on managed, platform‑agnostic data models with embedded data quality controls and versioned change management, it serves as the authoritative foundation for performance reviews, Investment Committee materials, and portfolio oversight.

Sample Data Questions Answered
- How is each portfolio company performing versus budget, forecast, and investment case?
- Where are material variances emerging?
- Which companies present upside or downside risk?
- How does performance compare across funds, sectors, and vintages?
- Which financial or operational drivers are impacting results?
- How has performance evolved QoQ and YoY?

Target Audience
- Investment Teams
- Portfolio Operations
- Fund Finance
- Investment Committee
- Senior Leadership
- Analytics & Data Governance functions
CREATE TABLE PLATINUM."PORTFOLIOPERFORMANCE" (
  "_ID" INTEGER AUTOINCREMENT PRIMARY KEY,
  "_PID" INTEGER REFERENCES PLATINUM."PORTFOLIOPERFORMANCE"("_ID"),
  "PORTFOLIOCOMPANYID" TEXT,
  "PORTFOLIOCOMPANYNAME" TEXT,
  "LEGALENTITYROLETYPE" TEXT,
  "LEGALENTITYKEYMETRICPERIOD" TEXT,
  "LEGALENTITYKEYMETRICSTART" TEXT,
  "LEGALENTITYKEYMETRICSEND" TEXT,
  "LEGALENTITYKEYMETRICTYPE" TEXT,
  "REVENUEACTUAL" TEXT,
  "LEGALENTITYKEYMETRICTYPE" TEXT,
  "REVENUEPLAN" TEXT,
  "EBITDAACTUALTYPE" TEXT,
  "EBITDAACTUAL" TEXT,
  "OPERATINGCASHFLOWACTUALTYPE" TEXT,
  "OPERATINGCASHFLOWACTUAL" TEXT,
  "NETDEBTACTUALTYPE" TEXT,
  "NETDEBTACTUAL" TEXT,
  "REVENUEPLANTYPE" TEXT,
  "REVENUEPLAN" TEXT,
  "EBITDAPLANTYPE" TEXT,
  "EBITDAPLAN" TEXT,
  "REVENUEVARIANCEVSPLANTYPE" TEXT,
  "REVENUEVARIANCEVSPLAN" TEXT,
  "EBITDAVARIANCEVSPLANTYPE" TEXT,
  "EBITDAVARIANCEVSPLAN" TEXT,
  "PERFORMANCESTATUSTYPE" TEXT,
  "PERFORMANCESTATUS" TEXT,
  "REVENUEGROWTHRATETYPE" TEXT,
  "REVENUEGROWTHRATE" TEXT,
  "CUSTOMERRETENTIONRATETYPE" TEXT,
  "CUSTOMERRETENTIONRATE" TEXT,
  "CASHCONVERSIONRATIOTYPE" TEXT,
  "CASHCONVERSIONRATIO" TEXT,
  "FINANCIALRISKFLAGTYPE" TEXT,
  "FINANCIALRISKFLAG" TEXT,
  "OPERATIONALRISKSCORETYPE" TEXT,
  "OPERATIONALRISKSCORE" TEXT,
  "CERTIFICATIONSCORETYPE" TEXT,
  "CERTIFICATIONSCORE" TEXT,
  "DATAQUALITYSCORETYPE" TEXT,
  "DATAQUALITYSCORE" TEXT
);

COMMENT ON TABLE PLATINUM."PORTFOLIOPERFORMANCE" IS '[DMP00000016] The Portfolio Company Performance Dataset is a Platinum‑layer, certified dataset providing a governed, consistent view of individual portfolio company performance across the firm. It standardizes financial metrics, operating KPIs, and performance‑versus‑plan measures, enabling trusted company‑level accountability and comparison across funds, sectors, and vintages. Built on managed, platform‑agnostic data models with embedded data quality controls and versioned change management, it serves as the authoritative foundation for performance reviews, Investment Committee materials, and portfolio oversight.  Sample Data Questions Answered - How is each portfolio company performing versus budget, forecast, and investment case? - Where are material variances emerging? - Which companies present upside or downside risk? - How does performance compare across funds, sectors, and vintages? - Which financial or operational drivers are impacting results? - How has performance evolved QoQ and YoY?  Target Audience - Investment Teams - Portfolio Operations - Fund Finance - Investment Committee - Senior Leadership - Analytics & Data Governance functions';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."_ID" IS 'Primary key - auto-generated surrogate identifier';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."_PID" IS 'Self-referential FK to parent record within this table (hierarchical)';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."PORTFOLIOCOMPANYID" IS 'DMA00000717';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."PORTFOLIOCOMPANYNAME" IS 'DMA00000689';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."LEGALENTITYROLETYPE" IS 'DMA00000787';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."LEGALENTITYKEYMETRICPERIOD" IS 'DMA00000821';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."LEGALENTITYKEYMETRICSTART" IS 'DMA00000822';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."LEGALENTITYKEYMETRICSEND" IS 'DMA00000823';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."LEGALENTITYKEYMETRICTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEACTUAL" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."LEGALENTITYKEYMETRICTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEPLAN" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."EBITDAACTUALTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."EBITDAACTUAL" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."OPERATINGCASHFLOWACTUALTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."OPERATINGCASHFLOWACTUAL" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."NETDEBTACTUALTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."NETDEBTACTUAL" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEPLANTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEPLAN" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."EBITDAPLANTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."EBITDAPLAN" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEVARIANCEVSPLANTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEVARIANCEVSPLAN" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."EBITDAVARIANCEVSPLANTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."EBITDAVARIANCEVSPLAN" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."PERFORMANCESTATUSTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."PERFORMANCESTATUS" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEGROWTHRATETYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."REVENUEGROWTHRATE" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."CUSTOMERRETENTIONRATETYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."CUSTOMERRETENTIONRATE" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."CASHCONVERSIONRATIOTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."CASHCONVERSIONRATIO" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."FINANCIALRISKFLAGTYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."FINANCIALRISKFLAG" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."OPERATIONALRISKSCORETYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."OPERATIONALRISKSCORE" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."CERTIFICATIONSCORETYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."CERTIFICATIONSCORE" IS 'DMA00000810';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."DATAQUALITYSCORETYPE" IS 'DMA00000809';
COMMENT ON COLUMN PLATINUM."PORTFOLIOPERFORMANCE"."DATAQUALITYSCORE" IS 'DMA00000810';