"""
jiraMdReport.py

Generates a combined Markdown report with three sections:
- Open Epics
- Stories Completed this Week
- Open Stories

Each section is generated by calling jira2mdtable.py with appropriate filters.
"""
import subprocess
import sys
import os
from datetime import datetime, timedelta
from pathlib import Path

def run_jira2mdtable(section_title, filters, fields=None, write_mode='overwrite'):
    cmd = [sys.executable, os.path.join(os.path.dirname(__file__), 'jira2mdtable.py')]
    if fields:
        cmd += ['--fields', fields]
    for f in filters:
        cmd += ['--filter', f]
    cmd += ['--title', section_title]
    cmd += ['--write-mode', write_mode]
    cmd += ['--output', 'ai-agile/02_generated_materials/jira/weekly_jira_status_report.md']
    subprocess.run(cmd, check=True)
    return None

def get_last_seven_days_range():
    from datetime import datetime, timedelta, time
    now = datetime.now()
    # End is last night at midnight (start of today)
    end = datetime.combine(now.date(), time.min)
    start = end - timedelta(days=6)
    return start.date().isoformat(), end.date().isoformat()

def main():

    # (Section moved to end of main)

    Path('ai-agile/02_generated_materials/jira').mkdir(parents=True, exist_ok=True)
    # Write H1 report title first with date range
    last7_start, last7_end = get_last_seven_days_range()
    report_path = Path('ai-agile/02_generated_materials/jira/weekly_jira_status_report.md')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(f'# Weekly Jira Status Report: {last7_start} - {last7_end}\n\n')
    # Section 1: Open Epics (append)
    run_jira2mdtable(
        'Open Epics',
        ['issuetype.name=Epic', 'Status!=Done'],
        write_mode='append'
    )
    # Section 2: Stories Completed in the Last 7 Days (append)
    last7_start, last7_end = get_last_seven_days_range()
    run_jira2mdtable(
        'Stories Completed in the Last 7 Days',
        [f'issuetype.name=Story', f'Status=Done', f'resolutiondate>={last7_start}', f'resolutiondate<={last7_end}'],
        write_mode='append'
    )

    # Section 3: Open Stories (append)
    run_jira2mdtable(
        'Open Stories',
        ['issuetype.name=Story', 'Status!=Done'],
        write_mode='append'
    )

    # Section 4: Pivot Table (Status by Assignee)
    # Use jira2mdpivot.py to append a pivot table of status by assignee
    pivot_cmd = [
        sys.executable,
        os.path.join(os.path.dirname(__file__), 'jira2mdpivot.py'),
        '--row-field', 'assignee',
        '--column-field', 'status',
        '--summary', 'count',
        '--title', 'Ticket Count by Assignee and Status',
        '--output', 'ai-agile/02_generated_materials/jira/weekly_jira_status_report.md'
    ]
    # Use append mode by reading, appending, and writing back
    # Instead, read the pivot output and append to the report
    import tempfile
    with tempfile.NamedTemporaryFile('w+', delete=False, suffix='.md') as tmpf:
        tmp_path = tmpf.name
    pivot_cmd[pivot_cmd.index('--output') + 1] = tmp_path
    subprocess.run(pivot_cmd, check=True)
    with open(tmp_path, 'r', encoding='utf-8') as pf, open('ai-agile/02_generated_materials/jira/weekly_jira_status_report.md', 'a', encoding='utf-8') as rf:
        rf.write('\n')
        rf.write(pf.read())
    os.remove(tmp_path)
    # Section 5: Completed by Person Over Last 8 Weeks (append at very end)
    from datetime import datetime, timedelta
    today = datetime.now().date()
    eight_weeks_ago = today - timedelta(weeks=8)
    pivot_cmd2 = [
        sys.executable,
        os.path.join(os.path.dirname(__file__), 'jira2mdpivot.py'),
        '--row-field', 'assignee',
        '--column-field', 'resolvedWeek',
        '--summary', 'count',
        '--title', 'Completed by Person Over Last 8 Weeks',
        '--filter', f'resolutiondate>={eight_weeks_ago.isoformat()}',
        '--filter', 'status=Done',
        '--output', 'ai-agile/02_generated_materials/jira/weekly_jira_status_report.md'
    ]
    import tempfile
    with tempfile.NamedTemporaryFile('w+', delete=False, suffix='.md') as tmpf2:
        tmp_path2 = tmpf2.name
    pivot_cmd2[pivot_cmd2.index('--output') + 1] = tmp_path2
    subprocess.run(pivot_cmd2, check=True)
    with open(tmp_path2, 'r', encoding='utf-8') as pf2, open('ai-agile/02_generated_materials/jira/weekly_jira_status_report.md', 'a', encoding='utf-8') as rf2:
        rf2.write('\n')
        rf2.write(pf2.read())
    os.remove(tmp_path2)
    print("Combined Jira report written to ai-agile/02_generated_materials/jira/weekly_jira_status_report.md.")

if __name__ == "__main__":
    main()
