"""
jiraMdReport.py

Generates a combined Markdown report with three sections:
- Open Epics
- Stories Completed this Week
- Open Stories

Each section is generated by calling jira2mdtable.py with appropriate filters.
"""
import subprocess
import sys
import os
from datetime import datetime, timedelta
from pathlib import Path

def run_jira2mdtable(section_title, filters, fields=None, write_mode='overwrite'):
    cmd = [sys.executable, os.path.join(os.path.dirname(__file__), 'jira2mdtable.py')]
    if fields:
        cmd += ['--fields', fields]
    for f in filters:
        cmd += ['--filter', f]
    cmd += ['--title', section_title]
    cmd += ['--write-mode', write_mode]
    cmd += ['--output', 'ai-agile/02_generated_materials/jira/weekly_jira_status_report.md']
    subprocess.run(cmd, check=True)
    return None

def get_last_seven_days_range():
    from datetime import datetime, timedelta, time
    now = datetime.now()
    # End is last night at midnight (start of today)
    end = datetime.combine(now.date(), time.min)
    start = end - timedelta(days=6)
    return start.date().isoformat(), end.date().isoformat()

def main():
    Path('ai-agile/02_generated_materials/jira').mkdir(parents=True, exist_ok=True)
    # Write H1 report title first with date range
    last7_start, last7_end = get_last_seven_days_range()
    report_path = Path('ai-agile/02_generated_materials/jira/weekly_jira_status_report.md')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(f'# Weekly Jira Status Report: {last7_start} - {last7_end}\n\n')
    # Section 1: Open Epics (append)
    run_jira2mdtable(
        'Open Epics',
        ['issuetype.name=Epic', 'Status!=Done'],
        write_mode='append'
    )
    # Section 2: Stories Completed in the Last 7 Days (append)
    last7_start, last7_end = get_last_seven_days_range()
    run_jira2mdtable(
        'Stories Completed in the Last 7 Days',
        [f'issuetype.name=Story', f'Status=Done', f'resolutiondate>={last7_start}', f'resolutiondate<={last7_end}'],
        write_mode='append'
    )
    # Section 3: Open Stories (append)
    run_jira2mdtable(
        'Open Stories',
        ['issuetype.name=Story', 'Status!=Done'],
        write_mode='append'
    )
    print("Combined Jira report written to ai-agile/02_generated_materials/jira/weekly_jira_status_report.md.")

if __name__ == "__main__":
    main()
